### ISSUE TITLE
Configure Desk Tracking

### ISSUE THREAD

**Issue by jeremyw24** [PlaceOS/docs#32]
- [ ] Configure Meraki
- [ ] Configure DNA Spaces
- [ ] People Finding with Meraki
- [ ] Locating users
- [ ] Capturing user devices
- [ ] Location Services overview

https://docs.google.com/document/d/1WJOAMgs8ZppFrIVzlkTWDiV8vgZ_KJf766XSpv9nnzw/edit#
